import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "my-app",
  description: "Generated by me",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
     <html lang="en">
      <body>
      <main>
        {children}
      </main>
      </body>
    </html>
  )
}